name = "counter-strike-2-tournament-zsz-wolsztyn"
type = "javascript"
compatibility_date = "2025-12-10"

[build]
command = "npm run build"
cwd = "./"

[assets]
directory = ".next/static"

[env.production]
routes = [
  { pattern = "cs2zsz.klovy.org", zone_id = "" }
]
